const fs = require('fs');
const path = require('path');

const dictPath = path.join(__dirname, '..', 'core', 'cursor-pt-dict.js');
let content = fs.readFileSync(dictPath, 'utf8');

const newTerms = {
  // SSH e Conexões Remotas
  'Select configured SSH host or enter an SSH destination': 'Selecione o host SSH configurado ou insira um destino SSH',
  'e.g. ubuntu@ec2-3-106-99.amazonaws.com, ssh -i key user@host, or named host below': 'ex.: ubuntu@ec2-3-106-99.amazonaws.com, ssh -i chave usuario@host ou host nomeado abaixo',
  'Add New SSH Host...': 'Adicionar Novo Host SSH...',
  'Configure SSH Hosts...': 'Configurar Hosts SSH...',
  'SSH Targets': 'Destinos SSH',
  'Connect to Host in New Window': 'Conectar ao Host em Nova Janela',
  'Connect to Host...': 'Conectar ao Host...',
  'Connect via SSH': 'Conectar via SSH',
  'SSH': 'SSH',
  'WSL': 'WSL',
  'Worktree': 'Worktree',
  'Worktree...': 'Worktree...',

  // Projetos, Repositórios e Welcome
  'Welcome to Cursor': 'Bem-vindo ao Cursor',
  'Early Access': 'Acesso Antecipado',
  'Introducing Projects': 'Apresentando Projetos',
  'Use projects to manage an entire work stream in one place. Agents in a project share one memory and task list.': 'Use projetos para gerenciar todo um fluxo de trabalho em um só lugar. Os agentes em um projeto compartilham uma mesma memória e lista de tarefas.',
  'Learn More': 'Saiba Mais',
  'Get Started': 'Começar',
  'Create Project': 'Criar Projeto',
  'Create a focused chat where Agents coordinate work': 'Crie um chat focado onde os Agentes coordenam o trabalho',
  'Search remote repos, cloud environments...': 'Pesquisar repositórios remotos, ambientes na nuvem...',
  'Select Multiple': 'Selecionar Múltiplos',
  'Repos': 'Repositórios',
  'Repositories': 'Repositórios',
  'Start from scratch': 'Começar do zero',
  'Loading Repositories...': 'Carregando Repositórios...',
  'Recent projects': 'Projetos recentes',
  'Open project': 'Abrir projeto',
  'Clone repo': 'Clonar repositório',
  'No Repo': 'Sem Repositório',
  'Connect your Repos to Cursor': 'Conecte seus Repositórios ao Cursor',
  'Choose a folder for your new project': 'Escolha uma pasta para seu novo projeto',

  // Status Bar, Popover e Modelos
  'Cursor Tab': 'Cursor Tab',
  'Disable globally': 'Desativar globalmente',
  'Model': 'Modelo',
  'Snooze': 'Adiar',
  'Tab Stats: 0/0 (0%)': 'Estatísticas do Tab: 0/0 (0%)',
  'Agent Stats: 0/0 (0%)': 'Estatísticas do Agente: 0/0 (0%)',
  'No commit scored': 'Nenhum commit pontuado',
  'Free Plan': 'Plano Gratuito',
  'Upgrade': 'Atualizar',
  'Upgrade to a Pro account': 'Atualizar para uma conta Pro',
  'Upgrade to Pro': 'Atualizar para o Pro',
  'This PC': 'Este PC',
  'Multitask': 'Multitarefa',

  // Composer, Ideias e Prompts Rápidos
  'Plan changes': 'Planejar alterações',
  'Build from a design': 'Construir a partir de um design',
  'Turn a frame into working UI in this repo': 'Transforme um frame em interface funcional neste repositório',
  'Deploy my prototype': 'Implantar meu protótipo',
  'Put it on a live link anyone can open': 'Coloque em um link ativo que qualquer pessoa possa abrir',
  'Start with a plan': 'Começar com um plano',
  'Align on implementation before writing code': 'Alinhe a implementação antes de escrever código',
  'Debug an issue': 'Depurar um problema',
  'Find root causes and fix tricky bugs': 'Encontre as causas-raiz e corrija bugs difíceis',
  'Use /ask to research your codebase before starting code changes': 'Use /ask para pesquisar sua base de código antes de iniciar alterações de código',

  // Agente, Cloud Agent e Execução
  'New Agent': 'Novo Agente',
  'Replace Agent': 'Substituir Agente',
  'Create an agent to start working on tasks': 'Crie um agente para começar a trabalhar em tarefas',
  'Ask follow-ups to the Cloud Agent...': 'Pergunte ao Agente em Nuvem para dar continuidade...',
  'Apply changes locally': 'Aplicar alterações localmente',
  'Checkout branch locally': 'Fazer checkout do branch localmente',
  'Checkout & Move to Local': 'Fazer Checkout e Mover para Local',
  'Checkout branch and convert agent to local mode': 'Fazer checkout da branch e converter agente para o modo local',
  'Upgrade to use Cloud Agents': 'Faça upgrade para usar Agentes em Nuvem',
  'Failed to start Cloud Agent': 'Falha ao iniciar o Agente em Nuvem',
  'Failed to switch to Cloud Agent': 'Falha ao alternar para o Agente em Nuvem',
  'Failed to retry Cloud Agent': 'Falha ao tentar novamente o Agente em Nuvem',
  'Still running locally?': 'Ainda executando localmente?',
  'Move to Cloud to keep running longer without your computer open.': 'Mova para a Nuvem para continuar executando por mais tempo sem manter seu computador aberto.',
  'Connection looks slow': 'A conexão parece lenta',
  'Move to Cloud so the agent can keep running even if you disconnect.': 'Mova para a Nuvem para que o agente possa continuar executando mesmo se você se desconectar.',
  'Continue running in Cloud?': 'Continuar executando na Nuvem?',
  'Continue Locally': 'Continuar Localmente',
  'Full Local': 'Totalmente Local',
  'Use full local environment (non-VM running locally)': 'Usar ambiente local completo (sem VM, executando localmente)',
  'Fix in Agent': 'Corrigir no Agente',
  'Write your instructions for the agent here...': 'Escreva suas instruções para o agente aqui...',
  'Model to use for subagent tasks': 'Modelo a ser usado para tarefas de subagentes',
  'Wrap long lines in Agent chat code blocks.': 'Quebrar linhas longas em blocos de código do chat do Agente.',
  'Adjust the default behavior of sending a message while Agent is streaming': 'Ajustar o comportamento padrão de envio de mensagem enquanto o Agente está gerando texto',
  'Running Capabilities': 'Recursos em Execução',
  'Model Status': 'Status do Modelo',
  'Manage Usage': 'Gerenciar Uso',
  'View setup instructions': 'Exibir instruções de configuração',
  'Manage Environments': 'Gerenciar Ambientes',

  // Automações, Habilidades e Regras
  'Automations': 'Automações',
  'Fix CI, conflicts, and comments with full self driving': 'Corrija CI, conflitos e comentários com automação completa',
  'An AI teammate that works in your tools and comes back with finished work.': 'Um colega de equipe de IA que trabalha em suas ferramentas e retorna com o trabalho concluído.',
  'Automation name': 'Nome da automação',
  'Optional numeric team id used to scope team-visible automations.': 'ID numérico opcional da equipe para definir o escopo de automações visíveis para a equipe.',
  'Automation ID (UUID) of the Cursor Automation to fetch.': 'ID da automação (UUID) da Automação do Cursor a ser obtida.',
  'Display name for the Cursor Automation.': 'Nome de exibição da Automação do Cursor.',
  'Move Cursor rules and commands into Agent Skills.': 'Mover regras e comandos do Cursor para Habilidades de Agente.',
  'Skill name': 'Nome da habilidade',
  'Tells the agent when to use this skill': 'Informa ao agente quando usar esta habilidade',
  'Attach when files matching these patterns are read': 'Anexar quando arquivos correspondentes a estes padrões forem lidos',
  'Only runs when you invoke it explicitly': 'Só executa quando você invocar explicitamente',
  'Replace Skill': 'Substituir Habilidade',
  'Create a cursor rule from the highlighted text': 'Criar uma regra do Cursor a partir do texto destacado',
  'Open Rule': 'Abrir Regra',
  'Open the generated rule file': 'Abrir o arquivo de regra gerado',
  'Migrated User Rules': 'Regras do Usuário Migradas',

  // Ferramentas, MCP e Comandos
  'Delete file': 'Excluir arquivo',
  'Edit file': 'Editar arquivo',
  'Get MCP tools': 'Obter ferramentas MCP',
  'Find files': 'Localizar arquivos',
  'List directory': 'Listar diretório',
  'Read file': 'Ler arquivo',
  'Read lints': 'Ler avisos de lint',
  'Run command': 'Executar comando',
  'Semantic search': 'Pesquisa semântica',
  'Update todos': 'Atualizar tarefas',
  'Fetch webpage': 'Buscar página da web',
  'Search web': 'Pesquisar na web',
  'Ask question': 'Fazer pergunta',
  'Computer use': 'Uso do computador',
  'Create plan': 'Criar plano',
  'Generate image': 'Gerar imagem',
  'Read MCP resource': 'Ler recurso MCP',
  'Screen recording': 'Gravação de tela',
  'Switch mode': 'Alternar modo',
  'Tool call': 'Chamada de ferramenta',
  'Await task': 'Aguardar tarefa',
  'MCP App': 'Aplicativo MCP',
  'Approve this server': 'Aprovar este servidor',
  'MCP Notification': 'Notificação de MCP',
  'Run a shell command in the terminal.': 'Executar um comando shell no terminal.',
  'Submission blocked by hook': 'Envio bloqueado por hook',
  'File reading blocked by hook': 'Leitura de arquivo bloqueada por hook',
  'View Hooks': 'Exibir Hooks',

  // Git, Pull Requests e Controle de Versão
  'Squash merge': 'Merge com squash',
  'Squash all commits into one': 'Combinar todos os commits em um',
  'Rebase merge': 'Merge com rebase',
  'Rebase and merge commits': 'Aplicar rebase e mesclar commits',
  'Merge commit': 'Commit de mesclagem',
  'Create a merge commit': 'Criar um commit de mesclagem',
  'Create a new pull request': 'Criar um novo pull request',
  'Create Pull Request': 'Criar Pull Request',
  'Mark ready for review': 'Marcar como pronto para revisão',
  'Convert draft PR to open PR': 'Converter rascunho de PR em PR aberto',
  'Open pull request in browser': 'Abrir pull request no navegador',
  'Your branches': 'Seus branches',
  'Use commit hash': 'Usar hash do commit',
  'Created by Cursor': 'Criado pelo Cursor',
  'New worktree': 'Novo worktree',
  'Copy worktree path': 'Copiar caminho do worktree',
  'Open terminal in worktree': 'Abrir terminal no worktree',
  'Open from this branch': 'Abrir a partir deste branch',
  'Open from new branch': 'Abrir a partir de um novo branch',
  'Merge manually': 'Mesclar manualmente',
  'Stash changes': 'Guardar alterações no stash',
  'Git Not Initialized': 'Git Não Inicializado',
  'No Git Remote': 'Nenhum Remoto do Git',
  'Workspace Not at Git Root': 'Espaço de Trabalho Não Está na Raiz do Git',
  'Incorrect Branch': 'Branch Incorreto',
  'Push local branch to remote': 'Enviar branch local para o remoto (Push)',
  'Push branch to remote': 'Enviar branch para o remoto (Push)',
  'Failed to push branch': 'Falha ao enviar branch para o remoto',
  'Cursor File Blame': 'Anotação de Arquivo do Cursor (Blame)',
  'Score Commit for AI Content': 'Pontuar Commit para Conteúdo de IA',
  'Recent commits - Select Repositories': 'Commits recentes - Selecionar Repositórios',
  'Recent commits - Select Commits': 'Commits recentes - Selecionar Commits',
  'Recent commits': 'Commits recentes',
  'Files changed outside of conversations': 'Arquivos alterados fora das conversas',

  // Chat, Abas e Diálogos
  'Fork this chat': 'Bifurcar esta conversa',
  'Open chat in a new tab': 'Abrir conversa em uma nova aba',
  'Keep all pending changes': 'Manter todas as alterações pendentes',
  'Undo All': 'Desfazer Tudo',
  'Undo all pending changes': 'Desfazer todas as alterações pendentes',
  'Mark as Read': 'Marcar como Lido',
  'Mark chat as read': 'Marcar conversa como lida',
  'Marcar como Não Lido': 'Marcar como Não Lido',
  'Marcar chat como não lido': 'Marcar conversa como não lida',
  'Rename chat': 'Renomear conversa',
  'Rename Chat': 'Renomear Conversa',
  'Restore chat': 'Restaurar conversa',
  'Export Chat': 'Exportar Chat',
  'Import Chat': 'Importar Conversa',
  'Replace Chat': 'Substituir Conversa',
  'Toggle Chat Pane': 'Alternar Painel de Chat',
  'Investigate Error in Chat': 'Investigar Erro no Chat',
  'Close Chat': 'Fechar Conversa',
  'Close Other Chats': 'Fechar Outras Conversas',
  'Close Running Tab?': 'Fechar Aba em Execução?',
  'Reset Chat Mode to Default': 'Redefinir Modo de Chat para o Padrão',
  'Past Chats': 'Conversas Anteriores',
  'Move to New Chat': 'Mover para Nova Conversa',
  'Create Chat': 'Criar Conversa',
  'Open exported chat': 'Abrir conversa exportada',
  'Stop sharing': 'Parar compartilhamento',
  'All team members can access': 'Todos os membros da equipe podem acessar',
  'Anyone with the link can access': 'Qualquer pessoa com o link pode acessar',
  'Members can view': 'Membros podem visualizar',
  'All team members can view': 'Todos os membros da equipe podem visualizar',
  'Send to Chat': 'Enviar para o Chat',
  'Quick Question': 'Pergunta Rápida',
  'Chat history': 'Histórico do chat',
  'Ask Sidechat': 'Perguntar ao Sidechat',
  'Add File to Cursor Chat': 'Adicionar Arquivo ao Chat do Cursor',
  'Add File to New Cursor Chat': 'Adicionar Arquivo ao Novo Chat do Cursor',
  'Add Directory to Cursor Chat': 'Adicionar Diretório ao Chat do Cursor',
  'Add Directory to New Cursor Chat': 'Adicionar Diretório ao Novo Chat do Cursor',
  'Play a sound when a chat response is completed': 'Tocar um som quando uma resposta do chat for concluída',
  'Controls the maximum width in pixels of chat content.': 'Controla a largura máxima em pixels do conteúdo do chat.',
  'Files & Folders': 'Arquivos e Pastas',
  'View Source': 'Exibir Código-fonte',
  'Copy prompt': 'Copiar prompt',
  'Thumbs Up': 'Gostei',
  'Thumbs Down': 'Não Gostei',
  'Review changes': 'Revisar alterações',
  'Download Video': 'Baixar Vídeo',
  'Copy Table': 'Copiar Tabela',
  'Use development environment': 'Usar ambiente de desenvolvimento',
  'Use production environment': 'Usar ambiente de produção',
  'Incorrect Repository': 'Repositório Incorreto',
  'Too slow': 'Muito lento',
  'Todo description...': 'Descrição da tarefa...',
  'Start writing your plan...': 'Comece a escrever seu plano...',
  'Unlock 3x more usage on Agent & more': 'Desbloqueie 3x mais uso no Agente e muito mais',
  'Download request content': 'Baixar conteúdo da solicitação',
  'Retake Screenshot': 'Tirar Nova Captura de Tela',
  'Choose Image': 'Escolher Imagem',
  'Remove Screenshot': 'Remover Captura de Tela',
  'Describe the bug...': 'Descreva o bug...',
  'Reset zoom to 100%': 'Redefinir zoom para 100%',
  'Connection Failed': 'Falha na Conexão',
  'This site can\'t be reached': 'Não foi possível acessar este site',
  'This site can&#39;t be reached': 'Não foi possível acessar este site',
  'Please update your payment method to keep using Cursor.': 'Atualize sua forma de pagamento para continuar usando o Cursor.',
  'Payment Method Update Required': 'Atualização da Forma de Pagamento Necessária',
  'Re-authorize your UPI payment method to restore automatic payments': 'Autorize novamente seu método de pagamento UPI para restaurar os pagamentos automáticos',
  'Plan ending soon': 'Plano terminando em breve',
  'Auto has significantly higher usage limits': 'Auto tem limites de uso significativamente maiores',
  'Switched to Auto, which provides significantly higher usage limits.': 'Alternado para Auto, que fornece limites de uso significativamente maiores.',
  'Revert Files': 'Reverter Arquivos',
  'Keep Files': 'Manter Arquivos',
  'Resubmit for all agents': 'Reenviar para todos os agentes',
  'Disable Inline Diffs': 'Desativar Diferenças Embutidas',
  'Use Cursor Browser': 'Usar Navegador do Cursor',
  'Use External Browser': 'Usar Navegador Externo',
  'Do not use browser': 'Não usar navegador',
  'Open in Cursor Browser': 'Abrir no Navegador do Cursor',
  'Unable to render': 'Não foi possível renderizar',
  'Mermaid Editor': 'Editor Mermaid',
  'Find in page': 'Localizar na página',
  'Save Error': 'Erro ao Salvar',
  'Login to Cursor': 'Entrar no Cursor',
  'Fuzzy search': 'Busca difusa (Fuzzy)',
  'Highlighted line': 'Linha destacada',
  'My Task': 'Minha Tarefa',
  'Task definition file': 'Arquivo de definição de tarefa',
  'Use themed background colors for inline diffs': 'Usar cores de fundo com tema para diffs embutidos',
  'Enable Cmd+P / Ctrl+P shortcut for file picker in Composer': 'Ativar atalho Cmd+P / Ctrl+P para o seletor de arquivos no Composer',
  'Automatically save files in normal composers': 'Salvar arquivos automaticamente em composers normais',
  'Local Only': 'Apenas Local',
  'Find and Replace': 'Localizar e Substituir',
  'Go to End': 'Ir para o Final',
  'Select to End': 'Selecionar até o Final',
  'Move cursor to a logical position in the view': 'Mover o cursor para uma posição lógica na exibição',
  'Scroll editor in the given direction': 'Rolar o editor na direção fornecida',
  'Reveal the given line at the given logical position': 'Revelar a linha especificada na posição lógica informada',
  'Ordered list': 'Lista ordenada',
  'Bullet list': 'Lista com marcadores',
  'Inline code': 'Código em linha',
  'Code block': 'Bloco de código',
  'Open a new In-Editor Find Widget.': 'Abrir um novo widget de localização no editor.',
  'Blocked URL:': 'URL bloqueada:',
  'Register Close Tooltip': 'Registrar Tooltip de Fechamento',
  'Issuer:': 'Emissor:',
  'Subject:': 'Assunto:',
  'Valid:': 'Válido:',
  'Fingerprint:': 'Impressão digital:',
  'Claim': 'Reivindicar',
  'No intervals for this section.': 'Nenhum intervalo para esta seção.',
  'Interval': 'Intervalo',
  'Duration': 'Duração',
  'Marks': 'Marcas',
  'Marks timeline': 'Linha do tempo de marcas',
  'Mark': 'Marca',
  'Offset': 'Deslocamento',
  'Application database': 'Banco de dados do aplicativo',
  'Calculating': 'Calculando',
  'Events': 'Eventos',
  'Open Window': 'Abrir Janela',
  'Create Snapshot': 'Criar Instantâneo',
  'Attach': 'Anexar',
  'Detach': 'Desanexar',
  'Show Modal': 'Mostrar Janela Modal',
  'With Icon': 'Com Ícone',
  'No Icon': 'Sem Ícone',
  'Secondary': 'Secundário',
  'Text Only': 'Apenas Texto',
  'Danger': 'Perigo',
  'Focus Outline': 'Contorno de Foco',
  'Notification': 'Notificação',
  'Important Action': 'Ação Importante',
  'Check Status': 'Verificar Status',
  'Confirm Action': 'Confirmar Ação',
  'Are you sure you want to perform this action?': 'Tem certeza de que deseja executar esta ação?',
  'Cancel (esc)': 'Cancelar (esc)',
  'This action cannot be undone. Proceed anyway?': 'Esta ação não pode ser desfeita. Prosseguir mesmo assim?',
  'Remember Preference': 'Lembrar Preferência',
  'Would you like to remember this preference for future sessions?': 'Deseja lembrar esta preferência para sessões futuras?',
  'No (esc)': 'Não (esc)',
  'An error occurred while processing your request.': 'Ocorreu um erro ao processar sua solicitação.',
  'Delete All Data': 'Excluir Todos os Dados',
  'Basic Dialog': 'Diálogo Básico',
  'Warning Dialog': 'Diálogo de Aviso',
  'Error Dialog': 'Diálogo de Erro',
  'Don\'t Ask Again Dialog': 'Diálogo Não Perguntar Novamente',
  'State': 'Estado',
  'Approvals': 'Aprovações',
  'Delete Key': 'Excluir Chave',
  'Scroll to bottom': 'Rolar para o final',
  'Send Test Notification': 'Enviar Notificação de Teste',
  'Load': 'Carregar',
  'Close DevTools': 'Fechar Ferramentas do Desenvolvedor',
  'Primary': 'Primário',
  'Avg': 'Média',
  'Tour': 'Apresentação Guiada'
};

// Injetar novas traduções
const insertMarker = '"Use Sandbox instead": "Usar Sandbox em vez disso",';
if (content.includes(insertMarker)) {
  const jsonEntries = Object.entries(newTerms)
    .map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`)
    .join('\n');
  content = content.replace(insertMarker, insertMarker + '\n' + jsonEntries);
  console.log('[OK] Novas traduções injetadas em CURSOR_DICT.');
} else {
  console.log('[WARN] Marker nao encontrado, injetando no topo do CURSOR_DICT');
  content = content.replace('export const CURSOR_DICT = {', 'export const CURSOR_DICT = {\n' + Object.entries(newTerms).map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`).join('\n'));
}

// Otimizar o scanDomNode para ignorar editores, terminais e inputs pesados
const oldScanCode = "if (node.tagName === 'WEBVIEW') {";
const optimizedFilter = `const tag = node.tagName;
      if (tag === 'SCRIPT' || tag === 'STYLE' || tag === 'PRE' || tag === 'CODE') return;
      const cl = node.className;
      if (typeof cl === 'string' && (cl.includes('monaco-editor') || cl.includes('terminal') || cl.includes('xterm'))) return;

      if (node.tagName === 'WEBVIEW') {`;

if (!content.includes("cl.includes('monaco-editor')")) {
  content = content.replace(oldScanCode, optimizedFilter);
  console.log('[OK] scanDomNode otimizado com exclusao segura de Monaco e Terminal.');
}

// Remover setInterval pesado do final e retirar characterData: true
content = content.replace(
  `obs.observe(document.body, { childList: true, subtree: true, characterData: true });\n    scanDomNode(document.body);\n    setInterval(() => {\n      scanDomNode(document.body);\n    }, 1000);`,
  `obs.observe(document.body, { childList: true, subtree: true });\n    scanDomNode(document.body);`
);

content = content.replace(
  `subObs.observe(win.document.body, { childList: true, subtree: true, characterData: true });\n                scanDomNode(win.document.body);\n                win.setInterval(() => scanDomNode(win.document.body), 1000);`,
  `subObs.observe(win.document.body, { childList: true, subtree: true });\n                scanDomNode(win.document.body);`
);

fs.writeFileSync(dictPath, content, 'utf8');
console.log('[OK] cursor-pt-dict.js atualizado com sucesso!');
